name: ms-user-service
services:
  ms-user-service:
    container_name: ms-user-service
#    image: jonathangunawan30/ms-user-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    env_file:
      - .env
    depends_on:
      - ms-postgres
    networks:
      - ms-network

  ms-postgres:
    container_name: ms-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_user_service
    ports:
      - 5432:5432
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge